### PR TITLE
Update DETAILS.md

### PR DESCRIPTION
**Pull request by padli**
tes

### CODE REVIEW

**Comment by SunDi3yansyah** [comment]
yakin cuma 3 mas? stiker no 1 sudah habis mas. silakan lihat file
sticker/README.md

Kamis, 04 Februari 2016, khoirul padli <notifications@github.com> menulis:

> tes
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/GitIndonesia/members/pull/44
> Commit Summary
>
>    - Update DETAILS.md
>
> File Changes
>
>    - *M* DETAILS.md
>    <https://github.com/GitIndonesia/members/pull/44/files#diff-0> (7)
>
> Patch Links:
>
>    - https://github.com/GitIndonesia/members/pull/44.patch
>    - https://github.com/GitIndonesia/members/pull/44.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitIndonesia/members/pull/44>.
>


-- 
Dikirim dari iPhone

**Comment by padli** [comment]
editnya. gimana si. heheheh

**Comment by SunDi3yansyah** [comment]
lewat editor kesukaan mas nya terserah

Kamis, 04 Februari 2016, khoirul padli <notifications@github.com> menulis:

> editnya. gimana si. heheheh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitIndonesia/members/pull/44#issuecomment-179750690>.
>


-- 
Dikirim dari iPhone

**Comment by SunDi3yansyah** [comment]
Hai GitIndonesia/members,

Saya ingin menambahkan Anda ke jaringan profesional saya di LinkedIn.

- Cahyadi

Harap konfirmasi bahwa Anda mengenal Cahyadi: https://www.linkedin.com/e/v2?e=0-ipy24gor-dj&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=8z9sLuUv&invitationId=6153186095623389184








Anda mendapatkan undangan untuk terhubung. LinkedIn akan menggunakan alamat email untuk memberi saran ke anggota lainnya di fitur seperti Orang yang Mungkin Anda Kenal. Berhenti berlangganan di sini: https://www.linkedin.com/e/v2?e=0-ipy24gor-dj&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEX09Rm4C2NLgAAAVWSCVgTJvsvsy4Pyr0soiM7FTGHQr8uVGp4knAZ8TNIGIPQTRL3UvhJeNOs4CPjj-YcJgt7vHegzBfC4cVT-nQX9O79hmVzhG1WDZ_RMgUD8Q2RgY5ykmY9twZ8pbFRmP3jcMhKdimPZiVFHADoMv7EY48y_vNoVXsUsBeJT22ZagkSlwjI&eid=0-ipy24gor-dj


Email ini dikirimkan kepada reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ipy24gor-dj&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn dan logo LinkedIn adalah merek dagang terdaftar yang dimiliki oleh LinkedIn.

**Comment by SunDi3yansyah** [comment]
Hai GitIndonesia/members,

Saya ingin menambahkan Anda ke jaringan profesional saya di LinkedIn.

- Cahyadi

Harap konfirmasi bahwa Anda mengenal Cahyadi: https://www.linkedin.com/e/v2?e=0-ipy24c3h-i0&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=LuGfZ_dx&invitationId=6153186094587408384








Anda mendapatkan undangan untuk terhubung. LinkedIn akan menggunakan alamat email untuk memberi saran ke anggota lainnya di fitur seperti Orang yang Mungkin Anda Kenal. Berhenti berlangganan di sini: https://www.linkedin.com/e/v2?e=0-ipy24c3h-i0&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEoQOcYbzOTzwAAAVWSCT-feClU4UqXxceW0bvskSCqvt7m5mvVQtjfNZx1S8dmsvUD-Lp3T9mXnsteNXhAqjNjebcV9218061GbJR4wvOZltcI_2jsqUu59qS1ygCbxN5ac6lLA23SjLRcKXZjgDQyPN9KL833tUHKtxKZuvzal5eygVeA7ynJk5GiTplh7UzK&eid=0-ipy24c3h-i0


Email ini dikirimkan kepada reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ipy24c3h-i0&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn dan logo LinkedIn adalah merek dagang terdaftar yang dimiliki oleh LinkedIn.

**Comment by SunDi3yansyah** [comment]
Hi Khoirul,

The email address reply@reply.github.com was recently added to your LinkedIn account.

If you don&#39;t want that email associated with your account after all, here&#39;s how to remove it:

Type https://www.linkedin.com/e/v2?e=5ac1p1-ipyunjz9-kg&amp;t=nas&amp;midToken=AQGPEizEwg5B4w&amp;ek=security_add_email_notification into your browser
Sign in with your email address and password
Find Primary email in the upper left and click Change/Add
Click Remove next to the email address you&#39;re removing.

Thanks for using LinkedIn and for helping us to keep your account secure.
The LinkedIn Team



&copy; 2016 LinkedIn Ireland Limited. LinkedIn, the LinkedIn logo, and InMail are registered trademarks of LinkedIn Corporation in the United States and/or other countries. All rights reserved.



This email was intended for Khoirul Padli (Founder at Indonesian Projects). 
Learn why we included this: https://www.linkedin.com/e/v2?e=5ac1p1-ipyunjz9-kg&a=customerServiceUrl&midToken=AQGPEizEwg5B4w&ek=security_add_email_notification&articleId=4788

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=5ac1p1-ipyunjz9-kg&a=customerServiceUrl&midToken=AQGPEizEwg5B4w&ek=security_add_email_notification

LinkedIn is a registered business name of LinkedIn Ireland Limited.
Registered in Ireland as a private limited company, Company Number 477441
Registered Office: Wilton Plaza, Wilton Place, Dublin 2, Ireland

**Comment by SunDi3yansyah** [comment]
Hi Khoirul,

The email address reply@reply.github.com was recently added to your LinkedIn account.

If you don&#39;t want that email associated with your account after all, here&#39;s how to remove it:

Type https://www.linkedin.com/e/v2?e=5ac1p1-iq0jxcxe-n9&amp;t=nas&amp;midToken=AQGPEizEwg5B4w&amp;ek=security_add_email_notification into your browser
Sign in with your email address and password
Find Primary email in the upper left and click Change/Add
Click Remove next to the email address you&#39;re removing.

Thanks for using LinkedIn and for helping us to keep your account secure.
The LinkedIn Team



&copy; 2016 LinkedIn Ireland Limited. LinkedIn, the LinkedIn logo, and InMail are registered trademarks of LinkedIn Corporation in the United States and/or other countries. All rights reserved.



This email was intended for Khoirul Padli (Founder at Indonesian Projects). 
Learn why we included this: https://www.linkedin.com/e/v2?e=5ac1p1-iq0jxcxe-n9&a=customerServiceUrl&midToken=AQGPEizEwg5B4w&ek=security_add_email_notification&articleId=4788

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=5ac1p1-iq0jxcxe-n9&a=customerServiceUrl&midToken=AQGPEizEwg5B4w&ek=security_add_email_notification

LinkedIn is a registered business name of LinkedIn Ireland Limited.
Registered in Ireland as a private limited company, Company Number 477441
Registered Office: Wilton Plaza, Wilton Place, Dublin 2, Ireland

**Comment by SunDi3yansyah** [comment]
Cahyadi Triyansyah would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=4n0pla-iq8ycsdr-5w&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=8z9sLuUv&invitationId=6153186095623389184

View Cahyadi Triyansyah&#39;s profile: https://www.linkedin.com/e/v2?e=4n0pla-iq8ycsdr-5w&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=8z9sLuUv&invitationId=6153186095623389184





Anda mendapatkan undangan untuk terhubung. LinkedIn akan menggunakan alamat email untuk memberi saran ke anggota lainnya di fitur seperti Orang yang Mungkin Anda Kenal. Berhenti berlangganan di sini: https://www.linkedin.com/e/v2?e=4n0pla-iq8ycsdr-5w&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=4n0pla-iq8ycsdr-5w&loid=AQEdFceC0qusvgAAAVW566faiDgFLEihwATVGVYqocben7Z2KWDK2HzEECMTtYFRYLlLx1mrUWJ_970I96UskGC_qHD4KrNAmNoQtSDLOZK92g4Uvk536LopAAVa4KrpwzEFg_NkOX3hDq9RvYoebOggPXMEnPjTLomgyjliJdSblsooacZu7UEKfw-PQFtPkHsy

Email ini dikirimkan kepada reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=4n0pla-iq8ycsdr-5w&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn dan logo LinkedIn adalah merek dagang terdaftar yang dimiliki oleh LinkedIn.

**Comment by SunDi3yansyah** [comment]
Cahyadi Triyansyah would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=4n0pla-iqhrix59-1v&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=8z9sLuUv&invitationId=6153186095623389184

View Cahyadi Triyansyah&#39;s profile: https://www.linkedin.com/e/v2?e=4n0pla-iqhrix59-1v&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=8z9sLuUv&invitationId=6153186095623389184





Anda mendapatkan undangan untuk terhubung. LinkedIn akan menggunakan alamat email untuk memberi saran ke anggota lainnya di fitur seperti Orang yang Mungkin Anda Kenal. Berhenti berlangganan di sini: https://www.linkedin.com/e/v2?e=4n0pla-iqhrix59-1v&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=4n0pla-iqhrix59-1v&loid=AQGgaITgpGurtAAAAVXZwoH6l-Bmf_PVXBp9oCzvb739Dtu26QBEPSEm0jau85xiWNFoUDjnirV4tvyxmLXmF_WCHoa4WPRQ1s3oxbdosNZSGZRwCNpshpglsDkAOCtfJdxvBmeYIuweoARfBQ8RnHqIXKqHJyKUIyXkKTPRXQL60vAp_XlsL3rGfpWhhBMrdiYI

Email ini dikirimkan kepada reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=4n0pla-iqhrix59-1v&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn dan logo LinkedIn adalah merek dagang terdaftar yang dimiliki oleh LinkedIn.

**Pull request closed without merging**
